[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "eave-collector-django-orm"
version = "0.1.0"
requires-python = ">=3.12.0"
dependencies = [
  "Django",
  "eave-collector-core"
]